# Generated by Django 3.1.7 on 2021-05-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0010_districtdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobileno', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
